# Generated by Django 2.1.4 on 2021-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='REVIEWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('msg', models.TextField(null=True)),
                ('rate', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('phish', models.BooleanField(default=True)),
                ('occ', models.IntegerField(null=True)),
            ],
        ),
    ]
